/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GalleryRouteImport } from './routes/_gallery'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as GalleryIndexRouteImport } from './routes/_gallery/index'
import { Route as GalleryMediaIdRouteImport } from './routes/_gallery/media.$id'

const GalleryRoute = GalleryRouteImport.update({
  id: '/_gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GalleryRoute,
} as any)
const GalleryMediaIdRoute = GalleryMediaIdRouteImport.update({
  id: '/media/$id',
  path: '/media/$id',
  getParentRoute: () => GalleryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof GalleryIndexRoute
  '/settings': typeof SettingsRoute
  '/media/$id': typeof GalleryMediaIdRoute
}
export interface FileRoutesByTo {
  '/settings': typeof SettingsRoute
  '/': typeof GalleryIndexRoute
  '/media/$id': typeof GalleryMediaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_gallery': typeof GalleryRouteWithChildren
  '/settings': typeof SettingsRoute
  '/_gallery/': typeof GalleryIndexRoute
  '/_gallery/media/$id': typeof GalleryMediaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/settings' | '/media/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/settings' | '/' | '/media/$id'
  id:
    | '__root__'
    | '/_gallery'
    | '/settings'
    | '/_gallery/'
    | '/_gallery/media/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GalleryRoute: typeof GalleryRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_gallery': {
      id: '/_gallery'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_gallery/': {
      id: '/_gallery/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof GalleryRoute
    }
    '/_gallery/media/$id': {
      id: '/_gallery/media/$id'
      path: '/media/$id'
      fullPath: '/media/$id'
      preLoaderRoute: typeof GalleryMediaIdRouteImport
      parentRoute: typeof GalleryRoute
    }
  }
}

interface GalleryRouteChildren {
  GalleryIndexRoute: typeof GalleryIndexRoute
  GalleryMediaIdRoute: typeof GalleryMediaIdRoute
}

const GalleryRouteChildren: GalleryRouteChildren = {
  GalleryIndexRoute: GalleryIndexRoute,
  GalleryMediaIdRoute: GalleryMediaIdRoute,
}

const GalleryRouteWithChildren =
  GalleryRoute._addFileChildren(GalleryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  GalleryRoute: GalleryRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
